name: Lint Helm Charts

on:
  pull_request:
    branches:
      - master
    paths:
      - "helm/provisioner/**"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set-up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest

      - name: Set-up Python
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa
        with:
          python-version: "3.x"

      - name: Set-up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs=helm --charts=helm/provisioner --lint-conf=helm/lintconf.yaml --check-version-increment=false --validate-maintainers=false

      - name: Create Kind cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140

      - name: Run chart-testing (install)
        run: ct install --chart-dirs=helm --charts=helm/provisioner
